export const clientsData = [
    { src: "https://naya.co.ke/naya/img/client/coke.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/11.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/10.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/5.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/2.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/15.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/14.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/16.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/20.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/3.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/21.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/coke.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/11.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/10.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/5.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/2.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/15.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/14.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/8.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/16.png", type: "client" },
    { src: "https://naya.co.ke/naya/img/client/20.png", type: "partner" },
    { src: "https://naya.co.ke/naya/img/client/21.png", type: "client" },
];